# Redirect requests to /pubs/ (with no slug) to the landing page
[[redirects]]
  from = "/pubs/"
  to = "/"
  status = 301

# Match actual slugs for the game
[[redirects]]
  from = "/pubs/:slug"
  to = "/app/index.html"
  status = 200

# Redirects to success page for successful payments
  [[redirects]]
  from = "/success"
  to = "/success/success.html"
  status = 200

#Redirects to cancelled page for cancelled payments.
[[redirects]]
  from = "/cancelled"
  to = "/cancelled/cancelled.html"
  status = 200



#-----------------------------------------------------------------------
# Catch-all 404 rule - MUST GO LAST!!! - only for unhandled redirects
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
